
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.baseName }}-console
  namespace: {{ .Release.Namespace }}
  annotations:
    # From https://docs.min.io/enterprise/aistor-object-store/installation/kubernetes/load-balancing/
    #nginx.ingress.kubernetes.io/proxy-body-size: 130m
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ignore-invalid-headers: "false"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.baseName }}-console.{{ .Values.ingress.domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.baseName }}-console
                port:
                  number: 9443
            path: /
            pathType: Prefix

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.baseName }}
  namespace:  {{ .Release.Namespace }}
  annotations:
    # From https://docs.min.io/enterprise/aistor-object-store/installation/kubernetes/load-balancing/
    #nginx.ingress.kubernetes.io/proxy-body-size: 130m
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ignore-invalid-headers: "false"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.baseName }}.{{ .Values.ingress.domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.baseName }}
                port:
                  number: 9000
            path: /
            pathType: Prefix
