
{{ if and .Values.oidcClient.enabled .Values.oidcClient.privateClient }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oidcClient.secretName }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: clientSecret
type: Opaque
{{ end }}