

---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: kubocd-webhooks
  namespace: kubocd
spec:
  description: Second stage of kubocd installation
  application:
    repository: quay.io/kubocd/applications/kubocd-webhooks
    tag: 0.1.0
    interval: 30m
  parameters:
    replicaCount: 1
  debug:
    dumpContext: true
