
---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: minio2
spec:
  description: S3 storage sever
  protected: false
  application:
    #repository: quay.io/kubocd/applications/minio
    repository: host.docker.internal:5001/applications/minio
    certSecretRef:
      name: certs-bundle
    tag: 0.1.0
    interval: 30s
  debug:
    dumpContext: true
  targetNamespace: minio2
  createNamespace: true
  parameters:
    rootUser: minio
    rootPassword: minio123
    storage:
      driveSize: 10G
    ingresses:
      public:
        enabled: true
      clearText:
        enabled: true
    vip:
      enabled: true
      host: minio2.kubo3.mbp
    environment:
      MINIO_IDENTITY_LDAP_SERVER_ADDR: "openldap-main.openldap.svc:636"
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN: "cn=admin,dc=odp,dc=com"
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD: "admin123"
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN: "ou=Users,dc=odp,dc=com"
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER: "(uid=%s)"
      MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN: "ou=Groups,dc=odp,dc=com"
      MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER: "(&(objectclass=posixGroup)(memberUid=%s))"
      MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY: "on"
      MINIO_IDENTITY_LDAP_SERVER_INSECURE: "off"
      MINIO_IDENTITY_LDAP_SERVER_STARTTLS: "off"
      MINIO_IDENTITY_LDAP_SRV_RECORD_NAME: ""
      MINIO_IDENTITY_LDAP_COMMENT: "in-cluster openldap server"
