
apiVersion: kubocd.kubotal.io/v1alpha1
kind: ClusterContract
metadata:
  name: cert-manager
spec:
  schema:
    properties:
      clusterIssuers:
        properties:
          public: { type: string, required: true }
          private: { type: string, required: true }
      trust:
        properties:
          issuerCaSecret:
            properties:
              name: { type: string, required: true }
              key: { type: string, required: true }
              type:  { type: string, required: false }




