
apiVersion: kubocd.kubotal.io/v1alpha1
kind: ClusterContract
metadata:
  name: ingress
spec:
  schema:
    properties:
      className: { type: string, required: true }
      domain: { type: string, required: true, description: "Used for FQDN building." }




