apiVersion: kubocd.kubotal.io/v1alpha1
kind: ClusterContract
metadata:
  name: redis-access
spec:
  schema:
    properties:
      host: { type: string, required: true }
      password: { type: string, required: true }



