apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baseName" . }}-admin-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.keycloak.admin.username }}
  password: "{{ .Values.keycloak.admin.password }}"