
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baseName" . }}-db-app
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.db.username }}"
  password: "{{ .Values.db.password }}"

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "baseName" . }}-db
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1

  storage:
    size: 20Gi

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: {{ include "baseName" . }}-db-app
