

apiVersion: v1alpha1
metadata:
  type: Application
  name: ingress-nginx
  version: 0.1.0
spec:
  contextSchema:
    properties:
      ingress:
        required: true
        properties:
          hostPostfix: { type: string, required: true}
  modules:
    - name: main
      source:
        helmRepository:
          url: https://kubernetes.github.io/ingress-nginx
          chart: ingress-nginx
          version: 4.12.1 # 4.10.0
      values: |
        controller:
          service:
            annotations:
              metallb.universe.tf/loadBalancerIPs: {{ resolveDNS .Context.ingress.hostPostfix }}
              metallb.universe.tf/allow-shared-ip: "ingress"
          extraArgs:
            enable-ssl-passthrough: true
        global:
          image:
            {{ $redirection := imageRedirect "registry.k8s.io/ingress-nginx" . }}        
            registry: {{ $redirection.registry }}
            # registry: registry.k8s.io
        controller:
          image:
            {{ $redirection := imageRedirect "registry.k8s.io/ingress-nginx/controller" . }}
            image: {{ $redirection.baseRepository }}
            # image: ingress-nginx/controller
        admissionWebhooks:
          patch:
            image:
               {{ $redirection := imageRedirect "registry.k8s.io/ingress-nginx/kube-webhook-certgen" . }}
              image: {{ $redirection.baseRepository }}
              # image: ingress-nginx/kube-webhook-certgen
        defaultBackend:
          image:
            {{ $redirection := imageRedirect "registry.k8s.io/defaultbackend-amd64" . }}
            image: {{ $redirection.baseRepository }}
            # image: defaultbackend-amd64
  dependencies:
    - loadBalancer
  roles:
    - ingress