---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seaweed.baseName" . }}-db-app
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.username }}"
  password: "{{ .Values.password }}"
