

apiVersion: v1alpha1
name: ingress-nginx
tag: 4.12.1-c01
protected: true
schema:
  parameters:
    properties:
      deployInControlPlane: { type: boolean, default: false }
      deployInServicePlane: { type: boolean, default: false }
      vip: { type: string }

modules:
  - name: noname
    timeout: 4m
    source:
      helmRepository:
        url: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
        version: 4.12.1 # 4.10.0
    values: |
      controller:
        {{- if .Parameters.deployInControlPlane }}
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        {{- end }}
        {{- if .Parameters.deployInServicePlane }}
        tolerations:
          - key: services.node-role.kubernetes.io
            operator: "Equal"
            effect: NoSchedule
            value: services
        nodeSelector:
          services.node-role.kubernetes.io: "services"
        {{- end }}
        image:
          image: ingress-nginx/controller
        service:
          annotations:
            metallb.universe.tf/loadBalancerIPs: {{ resolveDNS (.Parameters.vip | default (printf "ingress.%s" .Inputs.cluster.domain) ) }}
            metallb.universe.tf/allow-shared-ip: "ingress"
        extraArgs:
          enable-ssl-passthrough: true
      global:
      admissionWebhooks:
        patch:
          {{- if .Parameters.deployInControlPlane }}
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          {{- end }}
          {{- if .Parameters.deployInServicePlane }}
          tolerations:
            - key: services.node-role.kubernetes.io
              operator: "Equal"
              effect: NoSchedule
              value: services
          nodeSelector:
            services.node-role.kubernetes.io: "services"
          {{- end }}
          image:
             {{ $redirection := imageRedirect "registry.k8s.io/ingress-nginx/kube-webhook-certgen" . }}
            image: {{ $redirection.baseRepository }}
            # image: ingress-nginx/kube-webhook-certgen
      defaultBackend:
        {{- if .Parameters.deployInControlPlane }}
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        {{- end }}
        {{- if .Parameters.deployInServicePlane }}
        tolerations:
          - key: services.node-role.kubernetes.io
            operator: "Equal"
            effect: NoSchedule
            value: services
        nodeSelector:
          services.node-role.kubernetes.io: "services"
        {{- end }}
  

inputs:
  - contract: load-balancer
  - contract: cluster

outputs:
  - contract: ingress
    kind: ClusterConnection
    values:
      className: nginx
      domain: ingress.{{ .Inputs.cluster.domain }}

